### ISSUE TITLE
Fill property not working

### ISSUE THREAD

**Issue by bnussey** [yezarela/nativescript-image-cache#1]
Hello looks like the fill property is not working on iOS.. Reviewed the source code and can't see where it would be called.

**Comment by bnussey** [comment]
Logged PR for this.

**Comment by yezarela** [comment]
Thanks @bnussey for the PR. Already merged it !

**Comment by bnussey** [comment]
Awesome thanks @yezarela .
I did notice that the fill property set to stretch doesn't work exactly as `nativescript-web-image-cache` .. instead of filling to to the width/height of the container, it seems to fill much bigger, so you only see about 10-20% of the image. Any ideas what could be causing that?

**Comment by bnussey** [comment]
Have solved this with another submitted PR.. is it possible to get listed as contributor for this repo as its quite critical to our app.

**Comment by yezarela** [comment]
Awesome!, I've added you as collaborator for this repo and contributor on npm :+1:

**Comment by bnussey** [comment]
Thanks so much @yezarela ! Appreciate it.
