### ISSUE TITLE
iOS, rounded image issue

### ISSUE THREAD

**Issue by dvdbrk** [yezarela/nativescript-image-cache#11]
While

```
<NSImage row="0" col="0"  rounded="true" stretch="aspectFit" [src]="item.image"></NSImage>
```

works on Android, image is not round on iOS. I have tried 'radius' property as well, works on Android, doesn't on iOS. The example above is in the ListView, if it makes any difference. Any ideas?

**Comment by yezarela** [comment]
Hi @dvdbrk , rounded property only available on `android` , for `ios` you can just use `border-radius` property.
