### ISSUE TITLE
placeholderStretch is not working.

### ISSUE THREAD

**Issue by cagatayoncul** [yezarela/nativescript-image-cache#12]
Hi, do u have problem ? placeholderStretch is not working.

**Comment by yezarela** [comment]
Can you provide more details about what version/platform do you use?

**Comment by cagatayoncul** [comment]
i am using NS 3.3.0 on Android.

**Comment by yezarela** [comment]
Thanks @cagatayoncul , just fixed it in v1.1.0 release :+1:
