### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by dvdbrk** [yezarela/nativescript-image-cache#16]
If I add ```require("nativescript-image-cache");``` to **vendors.ts** file, because I'd like to put the plugin in the snapshot code - the webpack will fail with status:

```***** SNAPSHOT GENERATION FOR x86 FAILED! *****
# Script run failed in <embedded>@1740:1547
ReferenceError: com is not defined

#
# Fatal error in ../src/snapshot/mksnapshot.cc, line 175
# Check failed: blob.data.
#

Snapshot generation failed with the following error:
Error: Cannot find suitable v8 version! Original error: # Script run failed in <embedded>@1740:1547
ReferenceError: com is not defined

#
# Fatal error in ../src/snapshot/mksnapshot.cc, line 175
# Check failed: blob.data.
#

    at getV8Version.then.catch.error (/Users/dvdbrk/sample-app/node_modules/nativescript-dev-webpack/snapshot/android/project-snapshot-generator.js:254:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

Any ideas on how to optimise the plugin so it can be snapshotted? 

There is a great article on topic at https://www.nativescript.org/blog/improving-app-startup-time-on-android-with-webpack-v8-heap-snapshot. 

@sis0k0 has also done Firebase plugin optimisation (https://github.com/EddyVerbruggen/nativescript-plugin-firebase), but I am not sure how to apply the same changes to this plugin. 

Does anyone know at least how to debug the process?

**Comment by dvdbrk** [comment]
Thanks to @sis0k0 help on Slack, I've changed:

```
var proxy;

function getListener() {
  if (proxy) return proxy;

  if (typeof (com) !== "undefined" ){
    proxy = com.facebook.drawee.controller.BaseControllerListener.extend({
      _MyNSCachedImage: undefined,
      setMyNSCachedImage: function (img) {
        this._MyNSCachedImage = img;
      },
      onFinalImageSet: function (id, imageInfo, anim) {
        if (undefined != this._MyNSCachedImage) {
          this._MyNSCachedImage.isLoading = false;
        }
      },
      onIntermediateImageSet: function (id, imageInfo) { },
      onFailure: function (id, throwable) {
        console.log("onFailure", id, throwable);
      }
    });
  }

  return proxy;

}
```

and

```
var ProxyBaseControllerListener = getListener();
```

and added this check at few places:

```
function initialize() {
  if (typeof (com) !== "undefined"){
    com.facebook.drawee.backends.pipeline.Fresco.initialize(application.android.context);
  }
}
```

**and it works, snapshot does not report any issues! BUT** when I launch the app, I get the error every second time, the other time app fails to start at all.

```
d is not a constructor, undefined
```

😞

**Comment by sis0k0** [comment]
Hey @dvdbrk , try this branch https://github.com/yezarela/nativescript-image-cache/pull/17. Running the demo with webpack and snapshot is ok for me.

**Comment by dvdbrk** [comment]
Tested and all works! Thank you 👏 👏 👏
