### ISSUE TITLE
imageCache.clearDisk() is not a function - platform IOS

### ISSUE THREAD

**Issue by dali-gharbi** [yezarela/nativescript-image-cache#9]
Hi, 
**the issue occur on:**  ios
**the issue occur on the first run of the application after a fresh install**
**the issue occur with the following version numbers :**
"nativescript-image-cache": "^1.0.8",
CLI 3.2.1:
Cross-platform modules: 3.2.0
Runtime(s): "tns-ios": "3.2.0"
"tns-android": "3.2.0"

everytime i reinstall the application on ios i get the following error : 

> imageCache.clearDisk is not a function. (In 'imageCache.clearDisk()','imageCache.clearDisk' is undefined)
clearCache@file:///app/tns_modules/nativescript-image-cache/ns-imagecache.js:191:25
setCacheLimit@file:///app/tns_modules/nativescript-image-cache/ns-image-cache.js173:19
ngOnInit@file:///app/app.componenet.js:44:49

the error occur only one time on the first run and disappear if i close and reopen the app

**Comment by yezarela** [comment]
Thanks @crostina for reporting this, it seems that the library has removed the method on their latest release.. refer to this https://github.com/rs/SDWebImage/blob/master/Docs/SDWebImage-4.0-Migration-guide.md ... 
Do you mind for a PR?

**Comment by crostina** [comment]
Hi @yezarela  actually i don't have macOs i am building using the cloud Build service so i can't check if the change i make fix the problem on ios

```
function clearCache() {
    var imageCache = SDImageCache.sharedImageCache();
    imageCache.clearMemory();
    if ( typeof (imageCache.clearDisk) == 'undefined') {
        imageCache.deleteOldFilesWithCompletion();        
    } else {
        imageCache.clearDisk();
    }
}
exports.clearCache = clearCache;
```

**Comment by yezarela** [comment]
Hi @crostina , I have added your code and published it  to npm, can you try if that works?
It seems that I cannot reproduce your issue . Thanks

**Comment by crostina** [comment]
Hi @yezarela ,  unfortunately the new function is undefined too

>  imageCache.deleteOldFilesWithCompletion();   

so i made the change and test locally changing it with this will resolve the problèm :
```
exports.clearCache = function () {
    var imageCache = SDImageCache.sharedImageCache();
    imageCache.clearMemory();
    if (typeof imageCache.clearDisk == 'undefined') {
            imageCache.clearDiskOnCompletion(null);
    }
    else {
        imageCache.clearDisk();
    }
};
```
ps: null must be passed to clearDiskOnCompletion.

**Comment by yezarela** [comment]
Awesome @crostina !, I've published the fix to npm

**Comment by dali-gharbi** [comment]
@yezarela clearDiskOnCompletion()  is published without the null args 
it's returning error expecting 1 args and got 0

```
/**
 * Async clear all disk cached images. Non-blocking method - returns immediately.
 * @param completion    A block that should be executed after cache expiration completes (optional)
 */
- (void)clearDiskOnCompletion:(nullable SDWebImageNoParamsBlock)completion;
```

**Comment by yezarela** [comment]
ah sorry, i forgot that . Btw, updated !

**Comment by dali-gharbi** [comment]
@yezarela  thanks a lot 👍 💯
